name: dev

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      - name: checkout code repository
        uses: actions/checkout@v3

      - name: run pre-commit
        uses: pre-commit/action@v3.0.0

  tests:

    name: Python ${{ matrix.python-version }} ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        include:
          - environment-file: environment-dev.yml
            miniforge-variant: Mambaforge
            miniforge-version: 4.14.0-0

    defaults:
      run:
        shell: bash -l {0}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup conda environment with mambaforge
        uses: conda-incubator/setup-miniconda@v2
        with:
          use-mamba: true
          activate-environment: detectree-dev
          python-version: ${{ matrix.python-version }}
          condarc-file: ${{ matrix.condarc-file }}
          environment-file: ${{ matrix.environment-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}

      - name: install detectree
        run: |
          pip install .
          conda list
          conda info --all

      - name: test docs
        run: make -C ./docs html

      - name: test code
        run: |
          coverage run --source ./detectree --module pytest --verbose
          coverage xml -i
          coverage report -m

      - name: upload coverage report
        uses: codecov/codecov-action@v3
